# Site settings
title: Leonid Dinershtein
email: leonid@dinershtein.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dinershtein.com" # the base hostname & protocol for your site
twitter_username: leonid_diner
github_username: leoniddinershtein

# Build settings
markdown: kramdown
